Use actions-ecosystem/action-add/remove-labels
conda/actions pull request #75
Opened 2023-02-22 20:34 UTC by kenodegard

### Description

Instead of using a custom implementation of adding/removing labels, should we use the third-party action (https://github.com/actions-ecosystem/action-add-labels, https://github.com/actions-ecosystem/action-remove-labels)?

### Checklist - did you ...

- [ ] ~Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?~
     
- [ ] ~Add / update necessary tests?~
- [ ] ~Add / update outdated documentation?~

2023-03-01 16:28 UTC, jezdez commented
That's reasonable, https://github.com/actions-ecosystem is relatively well-known and trust-worthy. But as the GitHub docs mention, we should "harden" our use of GHA by referring to commit, not tags.

2023-03-01 16:30 UTC, jezdez requested changes
I wonder if we should only allow actions from certain GitHub orgs in the conda organization settings FWIW. That may put a scope to the risk maybe?

2023-03-01 16:30 UTC, jezdez commented on check-cla/action.yml
> -      uses: actions/github-script@v6
This would need to be updated to a commit

2023-03-01 16:30 UTC, jezdez commented on check-cla/action.yml
> -      uses: actions/github-script@v6
Same, commit needed here.

2023-03-01 17:57 UTC, dbast commented
related to that: Would be interesting to figure out how to update the pinned sha1s to newer tagged versions via dependabot/renovate ... dependabot seems to only supports .github/workflow/*.yml files... no composite action.yml support even though the syntax and versioning is the same.. not sure about renovate

2023-03-03 08:30 UTC, dbast approved these changes

2023-03-06 14:51 UTC, dbast approved these changes

2023-04-03 20:19 UTC, merged